version: '3'

services:
  cloudflare-updater:
    image: ghcr.io/rohit267/cloudflare-node-ddns:latest
    container_name: cloudflare-updater
    restart: unless-stopped
    volumes:
      - ./config.json:/app/config.json
    network_mode: "host"
