name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - uses: nyaa8/package-version@v1
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Build the Docker image
      run: |
        docker build . -t ghcr.io/rohit267/cloudflare-node-ddns:${env.PACKAGE_VERSION} -t ghcr.io/rohit267/cloudflare-node-ddns:latest
        docker push ghcr.io/rohit267/cloudflare-node-ddns:${env.PACKAGE_VERSION}
        docker push ghcr.io/rohit267/cloudflare-node-ddns:latest
